//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Nginx.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace NginxDotnetParser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="INginxListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class NginxBaseListener : INginxListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfig([NotNull] NginxParser.ConfigContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.config"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfig([NotNull] NginxParser.ConfigContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] NginxParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] NginxParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.genericStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericStatement([NotNull] NginxParser.GenericStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.genericStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericStatement([NotNull] NginxParser.GenericStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.regexHeaderStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegexHeaderStatement([NotNull] NginxParser.RegexHeaderStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.regexHeaderStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegexHeaderStatement([NotNull] NginxParser.RegexHeaderStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] NginxParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] NginxParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.genericBlockHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericBlockHeader([NotNull] NginxParser.GenericBlockHeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.genericBlockHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericBlockHeader([NotNull] NginxParser.GenericBlockHeaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] NginxParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] NginxParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.if_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_body([NotNull] NginxParser.If_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.if_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_body([NotNull] NginxParser.If_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.regexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegexp([NotNull] NginxParser.RegexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.regexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegexp([NotNull] NginxParser.RegexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.locationBlockHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocationBlockHeader([NotNull] NginxParser.LocationBlockHeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.locationBlockHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocationBlockHeader([NotNull] NginxParser.LocationBlockHeaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NginxParser.rewriteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRewriteStatement([NotNull] NginxParser.RewriteStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NginxParser.rewriteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRewriteStatement([NotNull] NginxParser.RewriteStatementContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace NginxDotnetParser
